//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koopakiller.Apps.Picosmos.Explorer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplexRelation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SourceTableName { get; set; }
        public string TargetTableName { get; set; }
        public string RelationDescriptor { get; set; }
    }
}
