//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koopakiller.Apps.Picosmos.Explorer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Explorer_CircularReferences
    {
        public int Id { get; set; }
        public int ChainId { get; set; }
        public int ChainPosition { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
    }
}
