//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koopakiller.Apps.Picosmos.Explorer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Human()
        {
            this.HumanGroups = new HashSet<HumanGroup>();
            this.HumanRelations = new HashSet<HumanRelation>();
            this.HumanRelations1 = new HashSet<HumanRelation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BirthPlaceId { get; set; }
        public Nullable<System.DateTime> BirthDateTime { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> ResumeId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Place Place { get; set; }
        public virtual Resume Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HumanGroup> HumanGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HumanRelation> HumanRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HumanRelation> HumanRelations1 { get; set; }
    }
}
