CREATE TABLE [dbo].[_Log](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [TimeStamp] [datetime] NULL,
    [Message] [nvarchar](max) NULL,
 CONSTRAINT [PK__Log] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
